import os

HF_TOKEN = os.getenv("HF_TOKEN")
if not HF_TOKEN:
    st.error("HF_TOKEN environment variable not set.")
    st.stop()

# Set env var explicitly — some older versions read from env only
os.environ["HF_TOKEN"] = HF_TOKEN

from huggingface_hub import InferenceClient

client = InferenceClient(provider="together")  # no api_key argument



import streamlit as st
import os
from langchain.document_loaders import Docx2txtLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from huggingface_hub import InferenceClient

# ---------------------------------
# CONFIGURATION
# ---------------------------------
SIMILARITY_THRESHOLD = 0.75  # Threshold to decide when to use document context
DOC_PATH = "data/sample.docx"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
LLM_MODEL = "moonshotai/Kimi-K2-Instruct-0905"

# Read Hugging Face token from environment variable
HF_TOKEN = os.getenv("HF_TOKEN")
if not HF_TOKEN:
    st.error("❌ HF_TOKEN environment variable not set. Please add it in Streamlit deployment settings (Secrets).")
    st.stop()

st.set_page_config(page_title="Chatbot", layout="centered")
st.title("Chatbot with Hugging Face Inference API")

# ---------------------------------
# SETUP HUGGINGFACE INFERENCE CLIENT
# ---------------------------------
client = InferenceClient(provider="together", api_key=HF_TOKEN)

# ---------------------------------
# LOAD EMBEDDINGS
# ---------------------------------
@st.cache_resource(show_spinner=True)
def load_embeddings():
    return HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)

embeddings = load_embeddings()

# ---------------------------------
# LOAD DOCUMENT & VECTORSTORE
# ---------------------------------
@st.cache_resource(show_spinner=True)
def load_vectorstore():
    if not os.path.exists(DOC_PATH):
        raise FileNotFoundError(f"{DOC_PATH} not found")

    loader = Docx2txtLoader(DOC_PATH)
    documents = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50
    )
    chunks = splitter.split_documents(documents)

    return FAISS.from_documents(chunks, embeddings)

vectorstore = load_vectorstore()

# ---------------------------------
# FUNCTION TO CALL LLM VIA API
# ---------------------------------
def call_llm_api(prompt: str) -> str:
    try:
        response = client.text_generation(
            model=LLM_MODEL,
            inputs=prompt,
            parameters={"max_new_tokens": 512, "temperature": 0.7},
        )

        if isinstance(response, list) and len(response) > 0:
            generated_text = response[0].get('generated_text', '')
        elif isinstance(response, dict):
            generated_text = response.get('generated_text', '')
        else:
            generated_text = ""

        if not generated_text:
            return "No answer generated by the model."

        return generated_text.strip()

    except Exception as e:
        return f"Error calling LLM API: {e}"

# ---------------------------------
# USER INPUT & PROCESSING
# ---------------------------------
question = st.text_input("Ask something", placeholder="Type your question here...")

if question:
    docs_scores = vectorstore.similarity_search_with_score(question, k=3)
    use_general_llm = True

    if docs_scores:
        best_score = docs_scores[0][1]
        # For FAISS distance score, lower means more similar
        if best_score <= SIMILARITY_THRESHOLD:
            use_general_llm = False

    if not use_general_llm:
        retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
        retrieved_docs = retriever.get_relevant_documents(question)
        context_text = "\n\n".join([doc.page_content for doc in retrieved_docs])

        prompt = (
            f"Use the following context to answer the question clearly:\n\n"
            f"{context_text}\n\nQuestion: {question}\nAnswer:"
        )

        answer = call_llm_api(prompt)
        st.markdown("### Answer (using documents)")
        st.write(answer)

    else:
        prompt = f"Answer the following question clearly and correctly:\n\nQuestion: {question}\nAnswer:"
        answer = call_llm_api(prompt)
        st.markdown("### Answer (general knowledge)")
        st.write(answer)
